lookahead_distance : 0.55 #staring distance
speed : 0.17 #maximum speed
expansion_size : 6 #wall expansion coefficient
target_error : 0.15 #margin of error to target
robot_r : 0.1 #robot distance for local security
